#!/usr/bin/env python3

import socket
import socketserver

class RFServer(socketserver.ThreadingTCPServer) :
    def server_bind(self) :
        self.socket.setsockopt(socket.SOL_SOCKET,
                               socket.SO_REUSEADDR, 1)
        self.socket.bind(self.server_address)

class ServerHandler(socketserver.StreamRequestHandler):

    def setup(self) :
        super().setup()
        print(f"setting up {self.client_address}")

    def handle(self):
        # First line contains mount point.
        self.mount_point = self.rfile.readline().strip()
        print('MountPoint~:', self.mount_point)

        while True :
            # Subsequent lines contain commands.
            self.data = self.rfile.readline()
            if not self.data : break # Connection closed.
            if self.data == b'unmount\n' : break
            print(f"{self.client_address} wrote:")
            print(self.data)
            self.wfile.write(self.data.upper())

    def finish(self) :
        print(f"closing connection with {self.client_address}")

if __name__ == "__main__":
    HOST, PORT = "localhost", 7897
    with RFServer((HOST, PORT), ServerHandler) as server:
        try :
            server.serve_forever()
        except KeyboardInterrupt :
            print("\rServer killed - exiting.")
