# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rservice.proto\"-\n\x0fMessagePathMode\x12\x0c\n\x04path\x18\x01 \x02(\t\x12\x0c\n\x04mode\x18\x02 \x02(\x05\"\x1c\n\rMessageString\x12\x0b\n\x03str\x18\x01 \x02(\t\"\x1d\n\x0cMessageReply\x12\r\n\x05\x65rrno\x18\x01 \x02(\x05\x32\x33\n\x07Greeter\x12(\n\x05mount\x12\x0e.MessageString\x1a\r.MessageReply\"\x00')
)




_MESSAGEPATHMODE = _descriptor.Descriptor(
  name='MessagePathMode',
  full_name='MessagePathMode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='MessagePathMode.path', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='MessagePathMode.mode', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=62,
)


_MESSAGESTRING = _descriptor.Descriptor(
  name='MessageString',
  full_name='MessageString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str', full_name='MessageString.str', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=92,
)


_MESSAGEREPLY = _descriptor.Descriptor(
  name='MessageReply',
  full_name='MessageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errno', full_name='MessageReply.errno', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['MessagePathMode'] = _MESSAGEPATHMODE
DESCRIPTOR.message_types_by_name['MessageString'] = _MESSAGESTRING
DESCRIPTOR.message_types_by_name['MessageReply'] = _MESSAGEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessagePathMode = _reflection.GeneratedProtocolMessageType('MessagePathMode', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEPATHMODE,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:MessagePathMode)
  ))
_sym_db.RegisterMessage(MessagePathMode)

MessageString = _reflection.GeneratedProtocolMessageType('MessageString', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGESTRING,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:MessageString)
  ))
_sym_db.RegisterMessage(MessageString)

MessageReply = _reflection.GeneratedProtocolMessageType('MessageReply', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEREPLY,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:MessageReply)
  ))
_sym_db.RegisterMessage(MessageReply)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=125,
  serialized_end=176,
  methods=[
  _descriptor.MethodDescriptor(
    name='mount',
    full_name='Greeter.mount',
    index=0,
    containing_service=None,
    input_type=_MESSAGESTRING,
    output_type=_MESSAGEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
