# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_pb2 as service__pb2


class GreeterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.fuse_access = channel.unary_unary(
        '/Greeter/fuse_access',
        request_serializer=service__pb2.MessageRequest.SerializeToString,
        response_deserializer=service__pb2.MessageReply.FromString,
        )
    self.fuse_readdir = channel.unary_unary(
        '/Greeter/fuse_readdir',
        request_serializer=service__pb2.MessageRequest.SerializeToString,
        response_deserializer=service__pb2.MessageReply.FromString,
        )
    self.fuse_getattr = channel.unary_unary(
        '/Greeter/fuse_getattr',
        request_serializer=service__pb2.MessageRequest.SerializeToString,
        response_deserializer=service__pb2.MessageReply.FromString,
        )


class GreeterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def fuse_access(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def fuse_readdir(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def fuse_getattr(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'fuse_access': grpc.unary_unary_rpc_method_handler(
          servicer.fuse_access,
          request_deserializer=service__pb2.MessageRequest.FromString,
          response_serializer=service__pb2.MessageReply.SerializeToString,
      ),
      'fuse_readdir': grpc.unary_unary_rpc_method_handler(
          servicer.fuse_readdir,
          request_deserializer=service__pb2.MessageRequest.FromString,
          response_serializer=service__pb2.MessageReply.SerializeToString,
      ),
      'fuse_getattr': grpc.unary_unary_rpc_method_handler(
          servicer.fuse_getattr,
          request_deserializer=service__pb2.MessageRequest.FromString,
          response_serializer=service__pb2.MessageReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
